version: 2
jobs:
  build:
    matrix:
      parameters:
        # TODO: Remove the deprecated legacy circleci/x image
        # https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
        image: [ "circleci/node:10", "cimg/node:10", "cimg/node:22"]
    working_directory: ~/repo
    docker:
      - image: image
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm run 2npm
            fi
workflows:
  version: 2
  build:
    jobs:
    - build:
        context: org-global
