
# https://circleci.com/docs/language-javascript
# https://circleci.com/developer/orbs/orb/circleci/node

version: 2.1
orbs:
  node: circleci/node@7.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
      - run:
          command: yarn build
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
