# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

name: ci
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['12.x', '18.x', '20.x', 'lts/*', 'latest']
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --check-files  # Force the upgrade of node-gyp.
    - run: yarn add standard
    - run: yarn lint  # Fails on lots of lint errors
      continue-on-error: true
    - run: yarn test  # "Error: no test specified" 
