# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

name: ci
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['10.x', '12.x', '18.x', '20.x', '22.x']
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --check-files
    - run: yarn add standard  # Fails with: `eslint-plugin-n needs Node.js >= 12` or 'gyp info using node-gyp@3.8.0' on modern Node.js.
      continue-on-error: true
    - run: npm install standard --global
    - run: yarn lint  # Fails with: 'standard' is not recognized as an internal or external command, operable program or batch file.
      # continue-on-error: true
    - run: yarn test  # "Error: no test specified" 
